### PR TITLE
Row schedular and kgsl govenor, seriously more performance

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by RonGokhale** [comment]
no row that's break WiFi and also incorrect author for row and kgsl commit

**Comment by RonGokhale** [comment]
no row that's break WiFi also author is incorrect in row and kgsl commit

**Comment by ghost** [comment]
Wifi is working

**Comment by antdking** [comment]
@RonGokhale I doubt the scheduler would break wifi, but at the state of the p350 wifi.. I wouldn't be surprised.

**Comment by ghost** [comment]
It's working on my p700 now, gallery loaded faster, but it is not completely stable, the kgsl simple govenor is stable, I was a bit to happy it was working

**Comment by RonGokhale** [comment]
@cybojenix initial row commit is fine but all  later row commits that need changes in block break wifi  
this best commit for adding row but breaks wifi 
https://github.com/CyanogenMod/android_kernel_samsung_msm8930-common/commit/060afe604b11a16603ec25872502d334a3d4cd70

**Comment by RonGokhale** [comment]
we have already talked about wifi breaking in irc many times

**Comment by antdking** [comment]
lol you know how much I pay attention on irc :L

**Comment by ghost** [comment]
Wifi isn't breaking now...

**Comment by RonGokhale** [comment]
kgsl commit is ok but give correct author faux123 is author 
https://github.com/TeamHackLG/lge-kernel-lproj/commit/f1a696b8443e25c3edbccd8c65ddc40ebff64464

**Comment by antdking** [comment]
I'm going to close this, as it needs to go on the experimental branch first, and the author's do need updating. discussions can carry on on irc if needed
http://webchat.freenode.net/?channels=#Lproj

**Comment by ghost** [comment]
Ok, sorry I'm justed started seriously using git

**Comment by antdking** [comment]
drop into the irc channel @bart452

**Comment by pinkflozd** [comment]
kgsl governor with a number of patches in experimental branch quite some time already

**Pull request closed without merging**
