### PR TITLE
L3 II (Single/Dual) - Vee3 Support

### PR DESCRIPTION
**Pull request by Caio99BR**
Erase those commits in brach jb4.3

Note: i workarounded the bug of broken fb0 in vee3, disabling splash_screen if CONFIG_MACH_MSM7X25A_V3_KK_WORKAROUD, these files are changed:
arch/arm/mach-msm/include/mach/board.h
drivers/video/msm/mdp.c
drivers/video/msm/mdp.h
drivers/video/msm/mdp4.h
drivers/video/msm/mdp_hw_init.c
drivers/video/msm/msm_fb.c
drivers/video/msm/msm_fb.h

### CODE REVIEW

**Comment by RonGokhale** [comment]
what's up with kcal ? using simplified one or not working on l7's ? and fix your sepolicy's.

**Comment by Caio99BR** [comment]
KCal not work, and part of support has removed by you in FB update, and what is problem with SEPolicy's.

**Comment by Caio99BR** [comment]
?

**Comment by RonGokhale** [comment]
i mean fix sepolicy and stick to enforcing or set permissive in cmdline but not here

**Comment by Caio99BR** [comment]
OK, i will change this, i tested and now is not possible to change SELinux of permissive

**Comment by Caio99BR** [comment]
Fixed!

**Comment by RonGokhale** [comment]
hmm ? not interested in merging l3 II support now ?

**Comment by Caio99BR** [comment]
Error when building to L5, already fixed this, i will create a new pull request

**Pull request closed without merging**
