### PR TITLE
More user ram space

### PR DESCRIPTION
**Pull request by cr3pt**
More ram for user

### CODE REVIEW

**Comment by antdking** [comment]
will merge when it's been confirmed to work across all roms for l7 that use this branch

**Comment by RonGokhale** [comment]
taking ram from mdp will only create issues

**Comment by cr3pt** [comment]
Look in all my builds - in all I change this value.

**Comment by hecatae** [comment]
I agree with Ron.

**Comment by tudorsirb** [comment]
It can be incrased, but not too much. It's already to high in main branch and gives artefacts on LG logo. Also, IIRC,  there are some ION errors when raising the value too high. Will test this in the evening and see. I'll leave it open for the time being.

**Comment by cr3pt** [comment]
And after few fixes in kernel I can confirm increase ram to 405mb as possible - is fully compiled without and artefact's on LG logo.

**Comment by tudorsirb** [comment]
I'm considering lowering the value. 

P.S. Having some screen wakeup problems.

**Pull request closed without merging**
