### PR TITLE
[VEE3] Add CM Support

### PR DESCRIPTION
**Pull request by Caio99BR**

### CODE REVIEW

**Comment by RonGokhale** [comment]
you can disable lge stuff like factory,diag also switching to RGB565 may create problem later with hwc1.1+ and jb_mr1+ adreno blobs otherwise looks fine.

**Comment by Caio99BR** [comment]
Removed LGE Stuff and set default depth to RGBA8888

**Comment by Caio99BR** [comment]
Hey RonGokhale after compiling the kernel, I was testing, but the /dev/graphics/fb0 does not exist, just as there is no file in /sys/class/graphics then simply run out of video, caught in bootsplash, adb works normally
I think the problem is in /arch/arm/mach-msm/lge/vee3/board-msm7627a-display_vee3.c file, most do not know how to solve.

**Comment by Caio99BR** [comment]
The problem is among the commits 316,567 and 316,720.
The only significant change between these commits is the kk-ion

**Pull request closed without merging**
