### PR TITLE
L1 II (Single/Dual/Tri) - V1 Support

### PR DESCRIPTION
**Pull request by Caio99BR**
Includes:
Updated Build Script to Support V1
Removed scsi_wait_scan Module
Updated zCache and set default
Updated Workaround to all 2nd Generation
Regenerate all CM DefConfigs

### CODE REVIEW

**Comment by RonGokhale** [comment]
all 2nd gen ? l7 II need too ?

**Comment by Caio99BR** [comment]
I think yes.
But V1 need to be fix camera.
The tester of kernel is @chijure, he have L1 II and L7 II, but L7 II not have any latest Custom ROM using Dysplay CAF.

**Comment by Caio99BR** [comment]
The camera is probably something else

**Comment by Caio99BR** [comment]
I will BringUp Vee7 support and increase size of MDP and ADSP of V1 and Vee3

**Comment by Caio99BR** [comment]
Just support this.
It is prepared for those who want to use.
I've done the workaround, which made me lose a lot of time and neurons

**Pull request closed without merging**
