### PR TITLE
vee3/msm7x27a: Fix for braces around scalar initializer

### PR DESCRIPTION
**Pull request by Caio99BR**
Signed-off-by: Caio99BR caiooliveirafarias0@gmail.com

### CODE REVIEW

**Comment by RonGokhale** [comment]
create new defconfig like cyanogenmod_vee3_defconfig but don't touch lge defconfig, keept it stock and ion change pushed for remaining lge boards.

**Comment by Caio99BR** [comment]
https://github.com/TeamHackLG/lge-kernel-lproj/pull/15

**Comment by Caio99BR** [comment]
In file included from ../../../../../../kernel/lge/lproj/drivers/video/msm/msm_fb.c:52:0:
../../../../../../kernel/lge/lproj/drivers/video/msm/mdp4.h:834:50: error: redefinition of 'mdp4_dsi_cmd_on'
In file included from ../../../../../../kernel/lge/lproj/drivers/video/msm/msm_fb.h:48:0,
                 from ../../../../../../kernel/lge/lproj/drivers/video/msm/msm_fb.c:48:
../../../../../../kernel/lge/lproj/drivers/video/msm/mdp.h:818:50: note: previous definition of 'mdp4_dsi_cmd_on' was here

The problem would be that line in defconfig:

``` # CONFIG_FB_MSM_MIPI_DSI is not set ```

Because of a variable in the mdp4.h
In all other defconfigs (CyanogenMod) this line is active.

How do I solve?

**Comment by Caio99BR** [comment]
-#if defined(CONFIG_FB_MSM_MIPI_DSI) || defined (CONFIG_FB_MSM_EBI2) /_LGE_CHANGE : added EBI CONFIG for v3 lcd_/
+#ifdef CONFIG_FB_MSM_MIPI_DSI

commit a49abb2

**Pull request closed without merging**
